UnityEngine = CS.UnityEngine
Transform = UnityEngine.Transform
Destroy = UnityEngine.GameObject.Destroy
Animator = UnityEngine.Animator
Animator = UnityEngine.Animator
NavMeshAgent = UnityEngine.AI.NavMeshAgent
GameObject = UnityEngine.GameObject

EventListener = CS.EventListener
EventTrigger = UnityEngine.EventSystems.EventTrigger
EventTriggerType = UnityEngine.EventSystems.EventTriggerType
UI = UnityEngine.UI
WWW = UnityEngine.WWW
WWWForm = UnityEngine.WWWForm
Resources = UnityEngine.Resources
Input = UnityEngine.Input
Time = UnityEngine.Time
Color = UnityEngine.Color
SceneManager = UnityEngine.SceneManagement.SceneManager
KeyCode = UnityEngine.KeyCode
Space = UnityEngine.Space
Camera = UnityEngine.Camera
AI = UnityEngine.AI
Random = UnityEngine.Random
Rigidbody = UnityEngine.Rigidbody
Object = UnityEngine.Object
TextAsset = UnityEngine.TextAsset
Text = UnityEngine.UI.Text
Image = UnityEngine.UI.Image
Sprite = UnityEngine.Sprite
Ray = UnityEngine.Ray
RaycastHit = UnityEngine.RaycastHit
Physics = UnityEngine.Physics
Quaternion = UnityEngine.Quaternion
InputField = UnityEngine.UI.InputField
AssetBundleManager = UnityEngine.AssetBundleManager
Application = UnityEngine.Application
AssetBundle = UnityEngine.AssetBundle
AssetBundleManifest = UnityEngine.AssetBundleManifest
Camera = UnityEngine.Camera
Physics = UnityEngine.Physics
Sprite = UnityEngine.Sprite
Vector3 = UnityEngine.Vector3
Collider = UnityEngine.Collider
Distance = UnityEngine.Vector3.Distancea
PlayerPrefs = UnityEngine.PlayerPrefs
MeshRenderer = UnityEngine.MeshRenderer
Debug = UnityEngine.Debug
AudioSource = UnityEngine.AudioSource
Component = UnityEngine.Component
MonoBehaviour = UnityEngine.MonoBehaviour
RectTransform = UnityEngine.RectTransform
Button = UnityEngine.UI.Button

IO=CS.System.IO
String=CS.System.String
StringSplitOptions=CS.System.StringSplitOptions
Directory=IO.Directory
Path=IO.Path

UnityEditor=CS.UnityEditor
AssetImporter=UnityEditor.AssetImporter
BuildPipeline=UnityEditor.BuildPipeline
BuildAssetBundleOptions=UnityEditor.BuildAssetBundleOptions
BuildTarget=UnityEditor.BuildTarget

StringDispose=CS.StringDispose